all:
	g++ -I include/UI/ -I include/models/ -I include/services/ -I include/repositories -I include/exceptions -o main src/UI/*.cpp src/models/*.cpp src/services/*.cpp src/repositories/*.cpp src/exceptions/*.cpp main.cpp

